import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { Suspense } from "react";
import "./globals.css";
import { HeaderNav } from "./_components/header-nav";
import { SiteFooter } from "./_components/site-footer";
import { AnalyticsConsentBanner } from "./_components/analytics-consent-banner";
import { AnalyticsTracker } from "./_components/analytics-tracker";
import { normalizeLang } from "../i18n/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  const lang = normalizeLang(h.get("x-ui-lang"));

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col bg-gray-50">
          <Suspense fallback={null}>
            <HeaderNav />
          </Suspense>
          <Suspense fallback={null}>
            <AnalyticsTracker />
          </Suspense>
          <div className="flex-1">{children}</div>
          <Suspense fallback={null}>
            <SiteFooter />
          </Suspense>
          <Suspense fallback={null}>
            <AnalyticsConsentBanner />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
